export { default as DashboardLayout } from './DashboardLayout';
export { default as Landing } from './Landing';
export { default as HomeLayout } from './HomeLayout';
export { default as Register } from './Register';
export { default as Login } from './Login';
export { default as Error } from './Error';
export { default as Reports } from './Reports';
export { default as Home } from './Home';
export { default as EventTrackerController } from './EventTrackerController'
export { default as Profile } from './Profile';
export { default as Admin } from './Admin';
export { default as VacationRequest } from './VacationRequest';
export { default as MyRequests } from './MyRequests';
export { default as MyRequest } from './MyRequest';
export { default as AdminVacationRequests } from './AdminVacationRequests';
export { default as EditVacationRequest } from './EditVacationRequest';
export { default as DeleteEvents } from './DeleteEvents';
